package scrapy

import (
	"encoding/xml"
	"io/ioutil"
	"sync"
	"time"
)

type ItemInterfaceI interface {
	// add property
	Add(v interface{})
	Dumps() (String, error)
	Empty() bool
}

type Feeds struct {
	XMLName xml.Name `xml:"rss"`
	Version string   `xml:"version,attr"`
	Channel *Channel `xml:"channel"`
}

func (f *Feeds) Add(v interface{}) {
	switch v.(type) {
	case *Map:
		title := v.(*Map).Get("title").(string)
		link := v.(*Map).Get("url").(String)
		pubTime := v.(*Map).Get("pub_time").(string)
		desc := v.(*Map).Get("description").(string)
		x := &XmlItem{
			Title:       title,
			Link:        link.String(),
			PubData:     pubTime,
			Description: desc,
		}
		f.Channel.AddItem(x)
		f.Channel.LastBuildDate = time.Now().Format(timeFormat)
	}
}

func (f *Feeds) Empty() bool {
	return len(f.Channel.Item) == 0
}

type Channel struct {
	Title         string     `xml:"title"`
	Link          string     `xml:"link"`
	Description   string     `xml:"description"`
	LastBuildDate string     `xml:"lastBuildDate"`
	Item          []*XmlItem `xml:"item"`
	sync.RWMutex
}

func (c *Channel) AddItem(item *XmlItem) {
	c.Lock()
	defer c.Unlock()
	c.Item = append(c.Item, item)
}

func (c *Channel) AddLastPubTime(pub string) {
	c.LastBuildDate = pub
}

func (f *Feeds) Dumps() (String, error) {
	feeds, err := xml.Marshal(f)
	if err != nil {
		panic(err)
	}
	if err := ioutil.WriteFile("feeds.xml", feeds, 0666); err != nil {
		panic(err)
	}
	return String(feeds), err
}

type XmlItem struct {
	Title       string `json:"title" xml:"title" validate:"required"`
	Link        string `json:"link" xml:"link" validate:"required"`
	PubData     string `json:"pub_data" xml:"pubDate"`
	Description string `json:"description" xml:"description" validate:"required"`
}

func NewFeeds() *Feeds {
	return &Feeds{
		XMLName: xml.Name{Local: "rss"},
		Version: "1.0.0",
		Channel: &Channel{
			Title:       "go-scrapy generater rss",
			Link:        "http://go-scrapy.com",
			Description: "RSS page automatically generated by spider",
			Item:        []*XmlItem{},
		},
	}
}
